pipeline {
    agent any
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }
    stages {
        stage('Cleaning WorkSpace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/SyedAzherAli/tetris-react.git'
            }
        }
        stage('Trivy FS Scan') {
            steps {
                sh 'trivy fs --format table -o trivyfs.html .'
            }
        }
        stage('Sonarqube Analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh ''' 
                    $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=TetrisVersion1.0 \
                    -Dsonar.projectKey=TetrisVersion1.0 
                    '''
                }
            }
        }
        stage('Quality Check') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
                }
            }
        }
        stage('Docker Build') { 
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred') {
                        sh ''' 
                        docker system prune -f
                        docker container prune -f 
                        docker build -t tetrisv1 .
                        '''
                    } 
                }
            }
        }
        stage('Docker Tag and Push') { 
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred') {
                        sh '''
                        docker tag tetrisv1 syedazherali/tetrisv1:${BUILD_NUMBER}
                        docker push syedazherali/tetrisv1:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }
        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image --format table -o image.html syedazherali/tetrisv1:${BUILD_NUMBER}'
            }
        }
        // Deployment configuration 
        stage('Git Checkout') { 
            steps {
                git branch: 'main', url: 'https://github.com/SyedAzherAli/GitOps-manifest-files.git'
            }
        }
        stage('Update Deployment Files') {
            environment {
                GIT_REPO_NAME = "GitOps-manifest-files"
                GIT_USER_NAME = "syedazherali"
            }
            steps {
                dir('tetris-react') {
                    withCredentials([string(credentialsId: 'git-token', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                            git config user.email "syedazherali01@gmail.com"
                            git config user.name "syedazherali"
                            BUILD_NUMBER=${BUILD_NUMBER}
                            echo $BUILD_NUMBER
                            imageTag=$(grep -oP '(?<=tetrisv1:)[^ ]+' deployment-service.yml)
                            echo $imageTag
                            sed -i "s/tetrisv1:${imageTag}/tetrisv1:${BUILD_NUMBER}/" deployment-service.yml
                            git add deployment-service.yml
                            git commit -m "Update deployment Image to version \${BUILD_NUMBER}"
                            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                        '''
                    }
                }
            }
        }
    }
}
